service:
  name: stripe-connect-demo-server
  app: stripe-connect-demo-server
  org: rangle.io

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  tag:
    project: stripe-connect-demo-server
    createdBy: Douglas Petla

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
